# Generated by Django 2.2.4 on 2019-11-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ticket_seatno'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
